name: Release JAR on merge to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Debug Listar contenido del directorio raíz después del checkout
        run: |
          echo "Contenido del directorio actual ($(pwd)):"
          ls -la
          echo "---"

      - name: Debug Listar contenido de application/app-service
        # Nuevo paso de depuración para confirmar la existencia de la carpeta app-service anidada
        run: ls -R application/app-service || echo "Directorio 'application/app-service' no existe o está vacío."

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build JAR
        # ¡CORREGIDO! Path completo del subproyecto Gradle anidado
        run: ./gradlew app-service:clean :app-service:build

      - name: Mostrar archivos generados
        # ¡CORREGIDO! Ruta completa al directorio 'libs' dentro del subproyecto anidado
        run: ls -R application/app-service/build/libs || echo "Directorio vacío o no existe"

      - name: Generar tag único
        run: echo "TAG_NAME=v1.0.${{ github.run_number }}-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Crear y Subir Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body: "Release generado automáticamente"
          draft: false
          prerelease: false
          # ¡CORREGIDO! Ruta completa para los archivos JAR
          files: application/app-service/build/libs/*.jar
